### ISSUE TITLE
"REMOTE_USER" instead of "REMOTE_SERVER" for Shibboleth?

### ISSUE THREAD

**Issue by joergsteinkamp** [rdmorganiser/rdmo-docs-en#11]
Dear all,

Should it not be "REMOTE_USER" instead of "REMOTE_SERVER" in [docs/configuration/authentication/shibboleth.md](https://github.com/rdmorganiser/rdmo-docs-en/blob/master/docs/configuration/authentication/shibboleth.md)?

Thanks & kind regards
Jörg Steinkamp

**Comment by jochenklar** [comment]
Yes, thanks, I fixed it.
