### ISSUE TITLE
Dead link in plugins documentation

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/rdmo-docs-en#21]
There is a link to a non-existing github repository called rdmo-content in the plugins documentation:
https://github.com/rdmorganiser/rdmo-docs-en/blob/883283c8abc6725857e0b1805a5f13fdb40d47a2/docs/plugins/index.md?plain=1#L10

**Comment by MyPyDavid** [comment]
thanks! think it needs to be `[rdmo-catalog](https://github.com/rdmorganiser/rdmo-catalog)` instead
