### ISSUE TITLE
Update plugins documentation

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/rdmo-docs-en#34]
There are a few view classes mentioned here, that don't seem to exist anymore?

- ProjectCreateUploadView,
- ProjectCreateImportView
- ProjectUpdateUploadView
- ProjectUpdateImportView

https://github.com/rdmorganiser/rdmo-docs-en/blob/068696278b7dbb54477ecf71b44903cc3978770d/docs/plugins/index.md?plain=1#L87C10-L87C10

Is this correct?

**Comment by jochenklar** [comment]
Its now in https://github.com/rdmorganiser/rdmo/blob/master/rdmo/projects/views/project_create.py and https://github.com/rdmorganiser/rdmo/blob/master/rdmo/projects/views/project_update.py and https://github.com/rdmorganiser/rdmo/blob/master/rdmo/projects/mixins.py. We can remove `ProjectUpdateUploadView` and `ProjectUpdateImportView`. But maybe we remove the reference to the classes alltogehter.
